name: Build

on:
    push:
        branches: [main]
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always

jobs:
    windows:
        name: Build Windows latest
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo
            - uses: dtolnay/rust-toolchain@stable
            - name: Build Portal Planner
              run: cargo build --release
            - name: Upload release
              uses: actions/upload-artifact@v4
              with:
                  name: portal_planner_win64
                  path: target/release/portal_planner.exe

    linux:
        name: Build Linux latest
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo
            - uses: dtolnay/rust-toolchain@stable
            - name: Update apt
              run: sudo apt update
            - name: Install egui dependencies
              run: sudo apt install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
            - name: Install Rusty File Dialog dependencies
              run: sudo apt install libgtk-3-dev
            - name: Install XKB/XCB dev dependencies
              run: sudo apt install libxkbcommon-dev libxkbcommon-x11-dev libxcb1-dev libxcb-xinput-dev
            - name: Build Portal Planner
              run: cargo build --release
            - name: Make tarball
              run: tar -czf portal_planner_linux.tar.gz -C target/release portal_planner
            - name: Upload release
              uses: actions/upload-artifact@v4
              with:
                  name: portal_planner_linux
                  path: portal_planner_linux.tar.gz

    macos:
        name: Build macOS latest
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo
            - uses: dtolnay/rust-toolchain@stable
              with:
                  targets: x86_64-apple-darwin
            - name: Install cargo-bundle
              uses: baptiste0928/cargo-install@v3
              with:
                  crate: cargo-bundle
                  version: latest
            - name: Build Portal Planner (arm64)
              run: cargo build --release
            - name: Build Portal Planner (x86_64)
              run: cargo build --release --target=x86_64-apple-darwin
            - name: Merge universal binary
              run: lipo -create -output target/release/portal_planner target/x86_64-apple-darwin/release/portal_planner target/release/portal_planner
            - name: Make app
              run: CARGO_BUNDLE_SKIP_BUILD= cargo bundle --release --package portal_planner
            - name: Make tarball
              run: tar -czf portal_planner_macos.tar.gz -C target/release/bundle/osx "Portal Planner.app"
            - name: Upload app
              uses: actions/upload-artifact@v4
              with:
                  name: portal_planner_macos
                  path: portal_planner_macos.tar.gz
